language: php
php:
  - '5.6'

env:
  - DLM_PACKAGE_VERSION=1.0.$TRAVIS_BUILD_NUMBER

install:
  - php bin/composer.phar install -q -n

script:
  - vendor/bin/phing -f build.xml prepare.version release